# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10YgXmiLv0P51CwPu-ulCFEa2dXaAffLG
"""

import math

result= 101-34+67

print(result)

import math

result=12*7

print(result)

import math

result= 4*(7+9*3)

print(result)









