# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1stB4UyeA6Y5H3EHCe-XPn43435VmyHES
"""

A = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
A[1][2]

[A[0][2:],A[1][2:],A[3][2:]]

list(range(-9,199,4))

car = {
  "brand": "BMW",
  "color":"red",
  "fuel":"petrol",
  "year": 2018,
  "mileage":30000

}
print(car)

def c ():
  c=int(input("Enter temperture: "))
  k=(c-273.15)
  print("temperature in kelvin is:",k)

def sigmond(e):
 sigmond , i = 1 , 1
 while i <= e:
    sigmond += i
    i += 1
 print("The sum sigmond" , sigmond)