# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ma-FEZum0Ls0ew14dA4cK8SljZTekv63
"""

from sympy import *
n, x, y = symbols("n x y")

factor(x**3 - y**3)

solve(x**2 - 4 * x - 3 , x)

apart(1 / ((x + 1) * (x + 2)))

diff(cos(x), x)
-sin(x)

integrate(exp(-x), (x, 0, oo))

x_list = [-3, 1, 2]
y_list = symbols('a b c')
apply_finite_diff(1, x_list, y_list, 0)

limit(x / sin(x) , x , 0)

diff(x**2 - 7 * x + 8 , x)

N(pi , 50)

A , B = Matrix([[1 , -1] , [2 , 3]]) , Matrix([[0 , 2] , [3 , 3]])
A , B

integrate(x**4 , (x , 1 , 3))

2 * A + 4 * B

A*B

2 * A